import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  backlog: [{type: 'autogenerated', dirName: '.'}],

  comunicacao: [{type: 'autogenerated', dirName: '.'}],

  disc: [{type: 'autogenerated', dirName: '.'}],

  feedback: [{type: 'autogenerated', dirName: '.'}],

  metricas: [{type: 'autogenerated', dirName: '.'}],

  pmc: [{type: 'autogenerated', dirName: '.'}],

  team_topology: [{type: 'autogenerated', dirName: '.'}] 
};

export default sidebars;
